* NOTICE

This package has been superseded by the package [[https://github.com/kickingvegas/casual][casual]]. Please install the package ~casual~ from either [[https://melpa.org/#/casual][MELPA]] or [[https://stable.melpa.org/#/casual][MELPA stable]].

Upon installation and upgrade of ~casual~, this package will be uninstalled from your Emacs configuration. 

This repository should be treated as an archive. All future development on Casual Lib will be done in the [[https://github.com/kickingvegas/casual][Casual repository]].

* Casual Lib
Casual Lib is a library package used to support the Casual suite of user interfaces. 

* Requirements
Casual Lib requires Emacs 29.1+ and Transient 0.6.0+.

Casual Lib has been verified with the following configuration. 
- Emacs 29.4 (macOS 14.6.1, Ubuntu Linux 22.04.4 LTS)
- Transient 0.7.4  

* Install
Casual Lib is intended to be implicitly installed as a dependency to the Casual suite of packages. To take advantage of recent features in Transient, Casual Lib requires a more recent version of Transient than what is built-in to Emacs 29.4. In order to update your system to the most recent version of Transient from either [[https://melpa.org/#/transient][MELPA]] or [[https://elpa.gnu.org/packages/transient.html][ELPA]], customize the variable ~package-install-upgrade-built-in~ to ~t~.

As Transient is closely tied to Magit, installing the latest version of Magit (via [[https://elpa.nongnu.org/nongnu/magit.html][non-GNU ELPA]] or [[https://melpa.org/#/magit][MELPA]]) can also pick up the latest version of Transient.

* Sponsorship
If you enjoy using Casual Lib, consider making a modest financial contribution to help support its development and maintenance.

[[https://www.buymeacoffee.com/kickingvegas][file:docs/images/default-yellow.png]]


* Acknowledgments
A heartfelt thanks to all the contributors to [[https://github.com/magit/transient][Transient]]. Casual Lib would not be possible without your efforts.

